version:  '3'

services:
  safechatdb:
    image: postgres
    restart: unless-stopped
    # environment:
    #   POSTGRES_PASSWORD: S@f3 Ch@t Adm1n2
    #   POSTGRES_USER: SAFE_CHAT_ADMIN2
    #   POSTGRES_DB: SAFE_CHAT2
    volumes:
      - pgData:/var/lib/postgresql/data
    ports:
      - 5432:5432
  dbexplorer:
    image:  adminer
    restart: unless-stopped
    ports:
      - 3002:8080
  chat-mq:
    image: rabbitmq:3
    hostname: chat-mq
    restart:  unless-stopped
    ports:
      - 30013:5672
  rbmq-manager:
    image:  rabbitmq:3-management
    restart:  unless-stopped
    ports:
      - 30014:15672

volumes:
  pgData: