export const ActionTypes = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SAVE_ROOMS: "SAVE_ROOMS",
  GET_ROOM: "GET_ROOM",
  GET_ROOMS: "ROOMS",
  JOIN_ROOM: "JOIN_ROOM",
  TOGGLE_LOADING: "TOGGLE_LOADING",
  UPDATE_CONTEXT_MENU: "UPDATE_CONTEXT_MENU",
  UPDATE_MAIN_MENU: "UPDATE_MAIN_MENU",
  ADD_USER_TO_ROOM: "ADD_USER_TO_ROOM",
  REMOVE_USER_FROM_ROOM: "REMOVE_USER_FROM_ROOM"
};
