\c template1
CREATE EXTENSION IF NOT EXISTS citext;
CREATE USER "SAFE_CHAT_ADMIN" WITH PASSWORD 'S@f3 Ch@t Adm1n' CREATEDB ;
CREATE DATABASE "SAFE_CHAT" OWNER "SAFE_CHAT_ADMIN" ;
GRANT ALL PRIVILEGES ON DATABASE "SAFE_CHAT" TO "SAFE_CHAT_ADMIN";
